language: node_js
node_js:
  - "8.4.0"

services:
  - docker

before_install:
  - "docker-compose build"

script:
  - "docker-compose -f docker-compose.yml -f docker-compose.test.yml run client -e NODE_ENV=test npm test"
  - "docker-compose -f docker-compose.yml -f docker-compose.test.yml run gateway -e NODE_ENV=test npm test"
  - "docker-compose -f docker-compose.yml -f docker-compose.test.yml run authentication -e NODE_ENV=test npm test"
  - "docker-compose -f docker-compose.yml -f docker-compose.test.yml run events -e NODE_ENV=test npm test"
  - "docker-compose -f docker-compose.yml -f docker-compose.test.yml run reservations -e NODE_ENV=test npm test"
  - "docker-compose -f docker-compose.yml -f docker-compose.test.yml run room_reservations -e NODE_ENV=test npm test"

branches:
  only:
    - dev
    - master
