version: '3.2'
services:
  gateway:
    build: .
    env_file: .env
    links:
    - reservations
    - events
    - authentication
    - files
    - redis

  authentication:
    build: ../services/authentication/
    env_file: ../services/authentication/.env
    links:
    - postgres
    - redis

  events:
    build: ../services/events/
    env_file: ../services/events/.env
    links:
    - postgres
    - redis

  reservations:
    build: ../services/reservations/
    env_file: ../services/reservations/.env
    links:
    - postgres
    - redis

  files:
    build: ../services/files/
    env_file: ../services/files/.env
    links:
    - postgres
    - redis

  room_reservations:
    build: ../services/room-reservations/
    env_file: ../services/room-reservations/.env
    links:
    - postgres
    - redis

  postgres:
    image: postgres
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=newshub
    ports:
    - "7000:5432"
    volumes:
    - postgres-data:/var/lib/postgresql/data
  
  client:
    build: ../client/
    ports:
    - "3030:3000"

volumes:
  postgres-data:
